### ISSUE TITLE
Error while calling endChat()

### ISSUE THREAD

**Issue by vivekjains** [zendesk/zopim-chat-web-sdk-sample-app#20] opened 2018-07-30 13:41 UTC
We are getting the error while calling endChat() to end the current chat session. Even we are not able to make out anything from the error display in logs.

Using Web-SDK 1.4.0

Error: Failed
    at eval (web-sdk.js?4b43:603)
    at e.$ (web-sdk.js?4b43:3014)
    at e.l [as fire] (web-sdk.js?4b43:840)
    at c.k.work (web-sdk.js?4b43:4125)
    at c.k.process (web-sdk.js?4b43:4097)
    at c.k.queueFrame (web-sdk.js?4b43:4090)
    at e.onmessage (web-sdk.js?4b43:3991)
    at e.socket.onmessage (web-sdk.js?4b43:3843)
    at WebSocket.t.onmessage (web-sdk.js?4b43:4289)

Not sure what's missing with our implementation.

**Comment by benjaminlgt** [comment] 2018-08-13 09:10
Hi @vivekjains, using Web SDK v1.4.0 I was unable to reproduce the error you are seeing. Could I have access to your code (or a pared down version that still has this issue) so that I may further debug the issue you are facing?

For me to be better able to assist you, please drop an email to `chat@zendesk.com` with the subject: `Attn: Benjamin Lee - Web SDK `. I'll close this issue for now.

**Closed as completed** 2018-08-13 10:05 UTC
